project:
  type: website

website:
  title: "Bugra in Deep"
  navbar:
    left:
      - text: "Notes from the Deep"
        href: index.qmd
    right:
      - about.qmd
      - icon: github
        text: GitHub
        href: https://github.com/BugraAKKUS
      - icon: twitter
        text: Twitter
        href: https://x.com/BugrainDeep
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/bugra-akkus/
      - icon: youtube
        text: YouTube
        href: https://www.youtube.com/@BugraInDeep

format:
  html:
    theme: darkly
    css: styles.css